
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "thunar"
local menu        = "walker"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
 hl.on("hyprland.start", function () 
   hl.exec_cmd("waybar & awww-daemon & pypr")
   hl.exec_cmd("elephant & walker --gapplication-service")
 end)

-- Run D-Bus updates on startup
hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Set GTK/Wayland environment variables
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
--[[
███████╗███████╗████████╗████████╗██╗███╗   ██╗ ██████╗ 
██╔════╝██╔════╝╚══██╔══╝╚══██╔══╝██║████╗  ██║██╔════╝ 
███████╗█████╗     ██║      ██║   ██║██╔██╗ ██║██║  ███╗
╚════██║██╔══╝     ██║      ██║   ██║██║╚██╗██║██║   ██║
███████║███████╗   ██║      ██║   ██║██║ ╚████║╚██████╔╝
╚══════╝╚══════╝   ╚═╝      ╚═╝   ╚═╝╚═╝  ╚═══╝ ╚═════╝ 
--]]
-- See: https://wiki.hypr.land/Configuring/Basics/Variables/

-- Pull colors for use in borders, groups, and plugins.
local C = dofile(os.getenv("HOME") .. "/.cache/hellwal/colors-hyprland.lua")

-- ---------------- General ----------------

hl.config({
    general = {
        gaps_in          = 4,
        gaps_out         = 8,
        border_size      = 2,
        resize_on_border = true,
        col = {
            active_border   = C.color7,
            inactive_border = C.color5,
        },
        layout = "dwindle",
    },
})

-- ---------------- Dwindle Layout ----------------
-- See: https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/

hl.config({
    dwindle = {
        preserve_split       = true,
        special_scale_factor = 0.8,
        default_split_ratio  = 1.3,
    },
})

-- ---------------- Master Layout ----------------
-- See: https://wiki.hypr.land/Configuring/Layouts/Master-Layout/

hl.config({
    master = {
        new_status = "slave",
        new_on_top = false,
        mfact      = 0.65,
    },
})

-- ---------------- Scrolling Layout ----------------
-- See: https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/

hl.config({
    scrolling = {
        direction                = "down",
        column_width             = 1.0,
        fullscreen_on_one_column = true,
        follow_focus             = true,
        follow_min_visible       = 0.25,
        focus_fit_method         = 1,
    },
})

-- ---------------- Custom Layout ----------------
-- See: https://wiki.hypr.land/Configuring/Layouts/Custom-Layouts/

--  Use as lua:columns
hl.layout.register("columns", {
    recalculate = function(ctx)
        local n = #ctx.targets
        if n == 0 then
            return
        end

        for i, target in ipairs(ctx.targets) do
            target:place(ctx:column(i, n))
        end
    end,
})

--  Use as lua:grid
hl.layout.register("grid", {
    recalculate = function(ctx)
        local n = #ctx.targets
        if n == 0 then
            return
        end

        local cols = math.ceil(math.sqrt(n))

        for i, target in ipairs(ctx.targets) do
            target:place(ctx:grid_cell(i, cols))
        end
    end,
})

-- ---------------- Group Settings ----------------

hl.config({
    group = {
        col = {
            border_active = {
                colors = { C.color4, C.color6, C.color7, C.color13, C.color15 },
                angle  = 40,
            },
        },
        groupbar = {
            col = {
                active   = C.color7,
                inactive = C.color2,
            },
            gradients                 = true,
            gaps_in                   = 5,
            gaps_out                  = 2,
            height                    = 12,
            indicator_height          = 0,
            font_size                 = 9,
            stacked                   = false,
            rounding                  = 2,
            gradient_rounding         = 6,
            gradient_round_only_edges = true,
        },
    },
})

-- ---------------- Decoration ----------------

hl.config({
    decoration = {
        rounding           = 8,
        active_opacity     = 1.0,
        inactive_opacity   = 0.9,
        fullscreen_opacity  = 1.0,
        dim_inactive       = true,
        dim_strength       = 0.1,
        dim_special        = 0.8,

        shadow = {
            enabled        = true,
            range          = 6,
            render_power   = 2,
            -- color          = "rgba(31, 32, 44, 0.6)",
            color          = "rgba(1f202c99)",
            -- color_inactive = "rgba(31, 32, 44, 0.3)",
            color_inactive = "rgba(1f202c4d)",
            offset         = { 4, 4 },
        },

        blur = {
            enabled           = true,
            size              = 5,
            passes            = 3,
            ignore_opacity    = true,
            new_optimizations = true,
            xray              = false,
            special           = true,
            noise             = 0.0117,
            vibrancy          = 0.1696,
        },
    },
})

-- ---------------- Animations ----------------
-- See: https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/

hl.config({ animations = { enabled = true } })

-- Bezier curves
hl.curve("myBezier",   { type = "bezier", points = { { 0.05, 0.9  }, { 0.1,  1.05  } } })
hl.curve("linear",     { type = "bezier", points = { { 0.0,  0.0  }, { 1.0,  1.0   } } })
hl.curve("wind",       { type = "bezier", points = { { 0.05, 0.9  }, { 0.1,  1.05  } } })
hl.curve("winIn",      { type = "bezier", points = { { 0.1,  1.1  }, { 0.1,  1.1   } } })
hl.curve("winOut",     { type = "bezier", points = { { 0.3,  -0.3 }, { 0,    1     } } })
hl.curve("slow",       { type = "bezier", points = { { 0,    0.85 }, { 0.3,  1     } } })
hl.curve("overshot",   { type = "bezier", points = { { 0.7,  0.6  }, { 0.1,  1.1   } } })
hl.curve("bounce",     { type = "bezier", points = { { 1.1,  1.6  }, { 0.1,  0.85  } } })
hl.curve("slingshot",  { type = "bezier", points = { { 1,    -1   }, { 0.15, 1.25  } } })
hl.curve("smoothOut",  { type = "bezier", points = { { 0.36, 0    }, { 0.66, -0.56 } } })
hl.curve("smoothIn",   { type = "bezier", points = { { 0.25, 1    }, { 0.5,  1     } } })
hl.curve("easeInSine", { type = "bezier", points = { { 0.005, 0.89 }, { 0.09, 0.91 } } })
hl.curve("rofi_curve", { type = "bezier", points = { { 0.34, -0.09 }, { 0,   0.96  } } })

-- Animations
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 5,   bezier = "winIn",   style = "gnomed"      }) --popin
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 5,   bezier = "winOut",  style = "gnomed"      }) --popin
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 5,   bezier = "wind",    style = "slide"      })
hl.animation({ leaf = "border",           enabled = true, speed = 10,  bezier = "linear"                        })
hl.animation({ leaf = "borderangle",      enabled = true, speed = 100, bezier = "linear",  style = "loop"       })
hl.animation({ leaf = "fade",             enabled = true, speed = 5,   bezier = "overshot"                      })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 5,   bezier = "wind"                          })
hl.animation({ leaf = "windows",          enabled = true, speed = 5,   bezier = "bounce",  style = "popin"      })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3,   bezier = "overshot", style = "slidevert" })
hl.animation({ leaf = "layersIn",         enabled = true, speed = 3,   bezier = "smoothIn", style = "slide top" })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 3,   bezier = "wind",     style = "slide top" })

-- ---------------- Input ----------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "grp:alt_shift_toggle",
        kb_rules   = "",
        repeat_rate  = 50,
        repeat_delay = 300,
        numlock_by_default          = false,
        left_handed                 = false,
        follow_mouse                = 1,    -- int: 0=none,1=always,2=detached,3=separate
        float_switch_override_focus = 0,    -- int: 0=off,1=on,2=on+float-to-float
        accel_profile               = "flat",

        -- touchpad = {
        --     disable_while_typing    = true,
        --     natural_scroll          = false,
        --     clickfinger_behavior    = false,
        --     middle_button_emulation = true,
        --     ["tap-to-click"]        = true,
        --     drag_lock               = false,
        -- },
    },
})

-- Gestures (uncomment to enable 3-finger swipe)
-- hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- ---------------- Miscellaneous ----------------

hl.config({
    misc = {
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms  = true,
        vrr                      = 0,    -- int: 0=off,1=on,2=fullscreen-only,3=fullscreen+game
        enable_swallow           = false,
        focus_on_activate        = false,
        render_unfocused_fps     = 30,
    },
})

-- ---------------- Bind Settings ----------------

hl.config({
    binds = {
        workspace_back_and_forth = true,
        allow_workspace_cycles   = true,
        pass_mouse_when_bound    = false,
    },
})

-- ---------------- Cursor ----------------

hl.config({
    cursor = {
        sync_gsettings_theme = true,
        no_hardware_cursors  = 1,    -- int: 0=use if possible,1=never,2=auto
        enable_hyprcursor    = true,
        no_warps             = true,
    },
})

-- ---------------- XWayland ----------------

hl.config({
    xwayland = {
        enabled            = true,
        force_zero_scaling = true,
    },
})

-- ---------------- Render ----------------

hl.config({
    render = {
        direct_scanout = 0,    -- int: 0=off,1=on,2=auto(game content)
    },
})

-- ---------------- Plugin Settings ----------------

 

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

hl.config({ animations = { enabled = true } })


-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})



---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + return", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("quickshell -c hyprquickpaper"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

hl.window_rule({
	name = "bluetooth",
	match = {class = "blueman-manager"},
	float = true,
	size = {"400", "600"},
	move = {"monitor_w - 500", "monitor_h-(monitor_h-50)"},
	animation = "slide top",
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})

hl.layer_rule({
	name = "walker-config",
	match = { namespace = "^walker$" },
	animation = 'slide-top'
})
